 version: "3.0"

 services:

        jenkins:

         container_name: jenkins

         user: 1000:900

         image: jenkins/jenkins:alpine

         ports:

          - 50000:50000

          - 8080:8080

         volumes:

           - ./pradeep:/var/jenkins_home:rw

           - /usr/bin/docker:/usr/bin/docker

           - /var/run/docker.sock:/var/run/docker.sock
